{% set name = "sphinx-toolbox" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_toolbox-{{ version }}.tar.gz
  sha256: 5c2ba14b60c90937964d49d196b7994966b198217457a2935a8c504db3e39926

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - whey >=0.0.20
  run:
    - apeye >=0.4.0
    - autodocsumm >=0.2.0
    - beautifulsoup4 >=4.9.1
    - cachecontrol >=0.12.6
    - dict2css >=0.2.3
    - docutils <0.18,>=0.16
    - domdf-python-tools >=2.9.0
    - html5lib >=1.1
    - lockfile >=0.12.2
    - python >=3.7
    - ruamel.yaml >=0.16.12
    - sphinx >=3.2.0
    - sphinx-autodoc-typehints >=1.11.1
    - sphinx-jinja2-compat >=0.1.0
    - sphinx-prompt >=1.1.0
    - sphinx-tabs <3.4.0,>=1.2.1
    - tabulate >=0.8.7
    - typing-extensions !=3.10.0.1,>=3.7.4.3
    - typing_inspect >=0.6.0

test:
  imports:
    - sphinx_toolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sphinx-toolbox/sphinx-toolbox
  summary: Box of handy tools for Sphinx 🧰 📔
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-toolbox.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
